/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.*;


/**
 *
 * @author kevdev
 */
public class Menu extends javax.swing.JFrame {
    private ActaVotaciones actaVotacionesPanel;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        initializeMenu(); 
        actaVotacionesPanel = new ActaVotaciones(); // Inicializamos el panel aquí

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     private void initializeMenu() {

        // Crear barra de menú
        JMenuBar menuBar = new JMenuBar();
        
        // Crear menús
        JMenu electionMenu = new JMenu("Gestión de Elecciones");
        JMenu candidateMenu = new JMenu("Gestión de Candidatos");
        JMenu voteMenu = new JMenu("Registro de Votos");
        JMenu tableMenu = new JMenu("Mesas Electorales");
        JMenu resultMenu = new JMenu("Conteo de Votos");
        JMenu reportMenu = new JMenu("Reportes e Informes");
        JMenu configMenu = new JMenu("Configuración y Seguridad");

        // Crear elementos del menú de ejemplo
        JMenuItem createElection = new JMenuItem("Crear Elección");
        JMenuItem modifyElection = new JMenuItem("Modificar Elección");
        JMenuItem deleteElection = new JMenuItem("Eliminar Elección");

        JMenuItem addCandidate = new JMenuItem("Agregar Candidato");
        JMenuItem modifyCandidate = new JMenuItem("Modificar Candidato");
        JMenuItem deleteCandidate = new JMenuItem("Eliminar Candidato");
        JMenuItem manageCandidates = new JMenuItem("Gestionar Candidatos");

        JMenuItem registerVote = new JMenuItem("Registrar Voto");
        JMenuItem viewResults = new JMenuItem("Ver Resultados");

        JMenuItem manageTable = new JMenuItem("Administrar Mesas");

        JMenuItem viewReports = new JMenuItem("Generar Reportes");

        JMenuItem settings = new JMenuItem("Configuración");
        JMenuItem logout = new JMenuItem("Cerrar Sesión");

        // Añadir los elementos a sus respectivos menús
        electionMenu.add(createElection);
        electionMenu.add(modifyElection);
        electionMenu.add(deleteElection);
        
        candidateMenu.add(addCandidate);
        candidateMenu.add(modifyCandidate);
        candidateMenu.add(deleteCandidate);

        voteMenu.add(registerVote);
        resultMenu.add(viewResults);

        tableMenu.add(manageTable);
        reportMenu.add(viewReports);

        configMenu.add(settings);
        configMenu.add(logout);

        // Añadir los menús a la barra de menú
        menuBar.add(electionMenu);
        menuBar.add(candidateMenu);
        menuBar.add(voteMenu);
        menuBar.add(tableMenu);
        menuBar.add(resultMenu);
        menuBar.add(reportMenu);
        menuBar.add(configMenu);

        // Configurar la barra de menú en el JFrame
        setJMenuBar(menuBar);
        
        createElection.addActionListener(e -> JOptionPane.showMessageDialog(this, "Crear Elección seleccionado"));
        modifyElection.addActionListener(e -> JOptionPane.showMessageDialog(this, "Modificar Elección seleccionado"));
        deleteElection.addActionListener(e -> JOptionPane.showMessageDialog(this, "Eliminar Elección seleccionado"));

        addCandidate.addActionListener(e -> JOptionPane.showMessageDialog(this, "Agregar Candidato seleccionado"));
        modifyCandidate.addActionListener(e -> JOptionPane.showMessageDialog(this, "Modificar Candidato seleccionado"));
        deleteCandidate.addActionListener(e -> JOptionPane.showMessageDialog(this, "Eliminar Candidato seleccionado"));

        registerVote.addActionListener(e -> JOptionPane.showMessageDialog(this, "Registrar Voto seleccionado"));
        viewResults.addActionListener(e -> JOptionPane.showMessageDialog(this, "Ver Resultados seleccionado"));

        manageTable.addActionListener(e -> JOptionPane.showMessageDialog(this, "Administrar Mesas seleccionado"));

        viewReports.addActionListener(e -> JOptionPane.showMessageDialog(this, "Generar Reportes seleccionado"));

        settings.addActionListener(e -> JOptionPane.showMessageDialog(this, "Configuración seleccionado"));
        logout.addActionListener(e -> JOptionPane.showMessageDialog(this, "Cerrar Sesión seleccionado"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Votación");
        setSize(600, 400);  // Tamaño de la ventana
        setLocationRelativeTo(null); 
        
        manageTable.addActionListener(e -> switchTActaVotaciones()); // New: Acción para el botón "Administrar Mesas"

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Votación");
        setSize(600, 400);  // Tamaño de la ventana
        setLocationRelativeTo(null);

        // Configuración de layout (ajustar el tamaño de la ventana si es necesario)
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    private void switchTActaVotaciones() {
        setContentPane(actaVotacionesPanel); // New: Cambia el JPanel al ActaVotaciones
        revalidate(); // New: Revalida el JFrame para actualizar la vista
        repaint(); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
